/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.system.form;

import com.system.DAO.ChucVuDAO;
import com.system.DAO.TaiKhoanDAO;
import com.system.component.Header;
import com.system.model.code.ChucVu;
import com.system.model.code.TaiKhoan;
import com.system.utils.Auth;

import com.system.utils.MsgBox;
import com.system.utils.XDate;
import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class QuanLyTaiKhoan extends javax.swing.JPanel {

    private Header header;
    public static int row = -1;
    TaiKhoanDAO daotk = new TaiKhoanDAO();
    ChucVuDAO daocv = new ChucVuDAO();
    DefaultTableModel tblModel;

    public QuanLyTaiKhoan(Header header) {
        initComponents();
        this.header = header;
        QuanLiNhanSu ns = new QuanLiNhanSu(this.header);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTenDangNhap = new com.system.customSwing.TextField_01.TextFieldSuggestion();
        txtMatKhau = new com.system.customSwing.TextField_01.TextFieldSuggestion();
        txtNgayTao = new com.system.customSwing.TextField_01.TextFieldSuggestion();
        cboTenChucVu = new com.system.customSwing.Designed.MyComboBox();
        txtMaNhanVien = new com.system.customSwing.TextField_01.TextFieldSuggestion();
        jPanel4 = new javax.swing.JPanel();
        btnLoad = new com.system.customSwing.Designed.MyButton_01();
        btnDeleteTK = new com.system.customSwing.Designed.MyButton_01();
        btnUpdateTK = new com.system.customSwing.Designed.MyButton_01();
        jPanel5 = new javax.swing.JPanel();
        tblTaiKhoan = new com.system.customSwing.Designed.MyTable();
        txtSearchTk = new com.system.customSwing.TextField_01.TextFieldSuggestion();
        myButton_011 = new com.system.customSwing.Designed.MyButton_01();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setOpaque(false);

        jPanel6.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tên đăng nhập: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mật khẩu:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Loại tài khoản: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mã nhân viên:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Ngày tạo:");

        txtTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDangNhapActionPerformed(evt);
            }
        });

        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });

        cboTenChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenChucVuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtTenDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboTenChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(62, 62, 62)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 279, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(845, 845, 845)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(38, 38, 38)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(cboTenChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(54, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 60, 0));

        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/system/icon/icons8-available-updates-70.png"))); // NOI18N
        btnLoad.setRadius(20);
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        jPanel4.add(btnLoad);

        btnDeleteTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/system/icon/icons8-remove-64.png"))); // NOI18N
        btnDeleteTK.setRadius(20);
        btnDeleteTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTKActionPerformed(evt);
            }
        });
        jPanel4.add(btnDeleteTK);

        btnUpdateTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/system/icon/icons8-edit-64.png"))); // NOI18N
        btnUpdateTK.setRadius(20);
        btnUpdateTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTKActionPerformed(evt);
            }
        });
        jPanel4.add(btnUpdateTK);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        tblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaiKhoanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(tblTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtSearchTk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchTkActionPerformed(evt);
            }
        });
        txtSearchTk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchTkKeyReleased(evt);
            }
        });

        myButton_011.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/system/icon/cong.png"))); // NOI18N
        myButton_011.setText("Tìm kiếm");
        myButton_011.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton_011ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearchTk, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myButton_011, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchTk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton_011, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ TÀI KHOẢN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchTkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchTkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchTkActionPerformed

    private void btnUpdateTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTKActionPerformed
        if (Auth.isManager()) {
            if (tblTaiKhoan.getTbl().getSelectedRowCount() >= 0) {
                try {
                    this.update();
                    this.clearTK();
                } catch (Exception e) {
                    System.out.println("Ngày tháng chưa dc cập nhật");
                }
            } else {
                MsgBox.alert(this, "Vui lòng thêm thông tin danh sách");
            }
        } else {
            MsgBox.alert(this, "Bạn không có cập nhật thông tin tai khoản");
        }
    }//GEN-LAST:event_btnUpdateTKActionPerformed

    private void btnDeleteTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTKActionPerformed
        try {
            this.delete();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteTKActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        this.clearTK();
    }//GEN-LAST:event_btnLoadActionPerformed

    private void cboTenChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTenChucVuActionPerformed

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void txtTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDangNhapActionPerformed

    private void txtSearchTkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchTkKeyReleased
        this.Search();
        if (txtSearchTk.getText().equals("")) {
            this.fillTableTK();
        }
    }//GEN-LAST:event_txtSearchTkKeyReleased

    private void tblTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTaiKhoanMouseClicked

    }//GEN-LAST:event_tblTaiKhoanMouseClicked

    private void myButton_011ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton_011ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton_011ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.system.customSwing.Designed.MyButton_01 btnDeleteTK;
    private com.system.customSwing.Designed.MyButton_01 btnLoad;
    private com.system.customSwing.Designed.MyButton_01 btnUpdateTK;
    private com.system.customSwing.Designed.MyComboBox cboTenChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private com.system.customSwing.Designed.MyButton_01 myButton_011;
    private com.system.customSwing.Designed.MyTable tblTaiKhoan;
    private com.system.customSwing.TextField_01.TextFieldSuggestion txtMaNhanVien;
    private com.system.customSwing.TextField_01.TextFieldSuggestion txtMatKhau;
    private com.system.customSwing.TextField_01.TextFieldSuggestion txtNgayTao;
    private com.system.customSwing.TextField_01.TextFieldSuggestion txtSearchTk;
    private com.system.customSwing.TextField_01.TextFieldSuggestion txtTenDangNhap;
    // End of variables declaration//GEN-END:variables

    private void init() {

        // gọi dữ liệu combobox
        this.fillTableTK();
        // load dữ liệu fill vào combobox nhé.
        this.fillTenChucVu();
        // ẩn đi các trường dữ liệu ko thể sửa
        // this.ShowEnabled();
        this.DataNow();
        // hám sử lí sự kiện click chuột
        this.clickTable();
        this.setStatus(true);

    }

    private void addColumn(DefaultTableModel model, String... nameColumn) {
        model.setColumnCount(0);
        for (int i = 0; i < nameColumn.length; i++) {
            model.addColumn(nameColumn[i]);
        }
    }

    //
    public void fillTableTK() {

        tblModel = new DefaultTableModel();
        addColumn(tblModel, "Mã nhân viên", "Tên đăng nhập", "Mật khẩu", "Mã chức vụ", "Ngày tạo");
        try {
            List<TaiKhoan> list = daotk.selectAll();// lưu cái cở sở dự liệu về ái list mà ở trong nhân viên            
            for (TaiKhoan entity : list) {
                tblModel.addRow(new Object[]{
                    entity.getMaNhanVien(), entity.getTenDangNhap(), entity.getMatKhau(), entity.getMaChucVu(), XDate.dateNow()

                });
            }
            tblTaiKhoan.getTbl().setModel(tblModel);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void insert() throws ParseException {

        try {
            //   if (validation()) {
            TaiKhoan qlnv = new TaiKhoan();
            TaiKhoan model = getFormTK(qlnv);
            if (MsgBox.confirm(this, "Bạn có chắc chắn muốn thêm nhân viên mới ?")) {
                daotk.insert(model);
                this.fillTableTK();
                this.clearTK();
                MsgBox.alert(this, "Thêm mới thành công!");
            }
            // }
        } catch (HeadlessException e) {
            MsgBox.alert(this, "Thêm mới thất bại!");
        }

    }

    public TaiKhoan getFormTK(TaiKhoan model) throws ParseException {
        model.setMaNhanVien(txtMaNhanVien.getText());
        model.setTenDangNhap(txtTenDangNhap.getText());
        model.setMatKhau(txtMatKhau.getText());
        String ngayTao = txtNgayTao.getText();
        model.setMaChucVu(cboTenChucVu.getSelectedIndex() + "");
        Date dateNS = new SimpleDateFormat("dd-MM-yyyy").parse(ngayTao);// chuyển ngày 
        model.setNgayTao(dateNS);
        ChucVu cv = (ChucVu) cboTenChucVu.getSelectedItem();
        model.setMaChucVu(cv.getMaChucVu());
//       
        return model;
    }
    // hàm để set giử liệu vào hoặc hiện thị lên form

    private void setFormTK(TaiKhoan model) throws ParseException {

        txtTenDangNhap.setText(model.getTenDangNhap());
        txtMatKhau.setText(model.getMatKhau());
        txtNgayTao.setText(tblTaiKhoan.getValueAt(this.row, 4).toString());
        txtMaNhanVien.setText(model.getMaNhanVien());
    }

    private void clearTK() {
        txtNgayTao.setText("");
        txtTenDangNhap.setText("");
        txtMatKhau.setText("");
        cboTenChucVu.setSelectedIndex(0);
        txtNgayTao.setText("");
    }

    private void editTK() {
        try {
            String maTK = tblTaiKhoan.getValueAt(row, 0).toString();
            TaiKhoan model = daotk.selectByID(maTK);
            if (model != null) {
                this.setFormTK(model);
                this.setStatus(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void setStatus(boolean insertable) {
//        btnUpdateTK.setEnabled(!insertable);
//        btnDeleteTK.setEnabled(!insertable);
        txtMatKhau.setEnabled(true);
        txtTenDangNhap.setEnabled(true);
        txtMaNhanVien.setEnabled(false);
        txtNgayTao.setEnabled(false);
        cboTenChucVu.setEnabled(false);
    }

    private void delete() {
        if (Auth.isManager()) {
            if (tblTaiKhoan.getTbl().getSelectedRowCount() > 0) {
                if (MsgBox.confirm(this, "Bạn thực sự muốn xóa thông tin tài khoản ?")) {
                    String maCV = (String) tblTaiKhoan.getValueAt(this.row, 0);
                    TaiKhoan cv = new TaiKhoan();
                    try {
                        daotk.delete(maCV);
                        this.fillTableTK();
                        this.clearTK();
                        MsgBox.alert(this, "Xóa thành công!");
                    } catch (Exception e) {
                        e.printStackTrace();
                        MsgBox.alert(this, "Xóa thất bại!");
                    }//

                }
            }
        } else {
            MsgBox.alert(this, "Bạn không có quyền xóa thông tin tài khoản");
        }

    }

    // phương thức dùng để chỉnh sửa
    private void update() {
        try {
            //    if (validation()) {
            TaiKhoan model = new TaiKhoan();
            this.getFormTK(model);
            if (MsgBox.confirm(this, "Bạn có chắc chắn muốn cập nhật thông tin?")) {
                daotk.update(model);
                this.fillTableTK();
                MsgBox.alert(this, "Cập nhật thành công!");
            }
            //  }
        } catch (Exception e) {
            System.out.println("Chưa cập nhật thông tin ngày tháng");
        }
    }

    public void fillTenChucVu() {
        ChucVuDAO cvd = new ChucVuDAO();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenChucVu.getModel();
        model.removeAllElements();
        List<ChucVu> list = cvd.selectAll();
        for (ChucVu item : list) {
            model.addElement(item);
        }

    }

    private void fillCickChucVu() {
        try {
            String maChucVu = tblTaiKhoan.getValueAt(this.row, 3).toString();
            ChucVuDAO cvd = new ChucVuDAO();
            List<ChucVu> list = new ArrayList<>();
            for (int i = 0; i < cboTenChucVu.getModel().getSize(); i++) {
                ChucVu cv1 = (ChucVu) cboTenChucVu.getModel().getElementAt(i);
                if (cv1.getMaChucVu().contains(maChucVu)) {
                    cboTenChucVu.setSelectedIndex(i);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void ShowEnabled() {
        cboTenChucVu.setEnabled(false);
        txtNgayTao.setEditable(false);
        txtNgayTao.setEnabled(false);
        // btnInsertTK.setEnabled(false);
        btnDeleteTK.setEnabled(false);
        btnUpdateTK.setEnabled(false);
    }

    // hàm để trả về ngày hiện tại nha
    private void DataNow() {
        // khởi động đồng hồ chạy
        //  Clock time = new Clock(lblTimeTK);
        //  time.start();
        //  XDate date = new XDate(lblDateTK);
        // date.start();
    }

    //hàm tìm kiếm
    private void Search() {
        try {
            String keyword = txtSearchTk.getText();
            if (keyword.matches("[a-zA-Z]+")) {//; trường hợp tìm theo tên 
                List<TaiKhoan> list = daotk.selectBykeywordName(keyword);
                tblModel = new DefaultTableModel();
                addColumn(tblModel, "Mã nhân viên", "Tên đăng nhập", "Mật khẩu", "Mã chức vụ", "Ngày tạo");
                for (TaiKhoan entity : list) {
                    tblModel.addRow(new Object[]{
                        entity.getMaNhanVien(), entity.getTenDangNhap(), entity.getMatKhau(), entity.getMaChucVu(), entity.getNgayTao()
                    });
                }
                tblTaiKhoan.getTbl().setModel(tblModel);
            } else {// trương hợp tìm theo số điện thoại
                List<TaiKhoan> list = daotk.selectBykeywordDate(keyword);
                tblModel = new DefaultTableModel();
                addColumn(tblModel, "Mã nhân viên", "Tên đăng nhập", "Mật khẩu", "Mã chức vụ", "Ngày tạo");
                for (TaiKhoan entity : list) {
                    tblModel.addRow(new Object[]{
                        entity.getMaNhanVien(), entity.getTenDangNhap(), entity.getMatKhau(), entity.getMaChucVu(), XDate.dateNow()
                    });
                }
                tblTaiKhoan.getTbl().setModel(tblModel);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    //
    private void clickTable() {

        tblTaiKhoan.getTbl().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
//                btnUpdateTK.setEnabled(true);
//                btnDeleteTK.setEnabled(true);
//                btnInsertTK.setEnabled(true);
                QuanLyTaiKhoan.row = tblTaiKhoan.getTbl().getSelectedRow();
                editTK();
                fillCickChucVu();
            }

        });
    }

}
