/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.system.customSwing.Designed;

import java.awt.Color;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class MyTable_Advance extends javax.swing.JPanel {

    /**
     * Creates new form MyTable
     */
    public MyTable_Advance() {
        initComponents();
        this.setBackground(Color.white); // getContentPane() là lấy cái JFrame
        com.system.customSwing.Table_Advance.TableCustom.apply(jScrollPane1, com.system.customSwing.Table_Advance.TableCustom.TableType.MULTI_LINE); // MulTi_Line sẽ giúp cho các ô sẽ tự xuống dòng khi mà độ dài ô không đủ
        loadDataToTable(tblList);
        tblList.setGridColor(new Color(230, 230, 230));
        tblList.setShowHorizontalLines(false);
    }
    
    private void loadDataToTable(JTable tbl) {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        // Xóa tất cả mọi thứ mặc định trên Table
        model.setColumnCount(0);
        model.setRowCount(0);
        
        // Tạo cột:
        model.addColumn("Mã số");
        model.addColumn("Họ và tên");
        model.addColumn("Giới tính");
        model.addColumn("Địa chỉ");
        model.addColumn("Số điện thoại");
        
        // Tạo dòng
        model.addRow(new Object[] {"PC04124", "Nguyễn Văn Hồng Phi", "Nam", "Trà Vinh", "0336761552"});
        model.addRow(new Object[] {"PC04012", "Huỳnh Bảo Khang", "Nam", "Cà Mau", "012345678"});
        model.addRow(new Object[] {"PC03916", "Nguyễn Thị Hồng Thắm", "Nữ", "Hậu Giang", "012345678"});
        model.addRow(new Object[] {"PC04104", "Phạm Văn Vương", "Nam", "Phú Quốc", "012345678"});
        model.addRow(new Object[] {"PC03762", "Phạm Văn Duy", "Nam", "Bạc Liêu", "012345678"});
        model.addRow(new Object[] {"PC04124", "Nguyễn Văn Hồng Phi", "Nam", "Trà Vinh", "0336761552"});
        model.addRow(new Object[] {"PC04012", "Huỳnh Bảo Khang", "Nam", "Cà Mau", "012345678"});
        model.addRow(new Object[] {"PC03916", "Nguyễn Thị Hồng Thắm", "Nữ", "Hậu Giang", "012345678"});
        model.addRow(new Object[] {"PC04104", "Phạm Văn Vương", "Nam", "Phú Quốc", "012345678"});
        model.addRow(new Object[] {"PC03762", "Phạm Văn Duy", "Nam", "Bạc Liêu", "012345678"});
        model.addRow(new Object[] {"PC04124", "Nguyễn Văn Hồng Phi", "Nam", "Trà Vinh", "0336761552"});
        model.addRow(new Object[] {"PC04012", "Huỳnh Bảo Khang", "Nam", "Cà Mau", "012345678"});
        model.addRow(new Object[] {"PC03916", "Nguyễn Thị Hồng Thắm", "Nữ", "Hậu Giang", "012345678"});
        model.addRow(new Object[] {"PC04104", "Phạm Văn Vương", "Nam", "Phú Quốc", "012345678"});
        model.addRow(new Object[] {"PC03762", "Phạm Văn Duy", "Nam", "Bạc Liêu", "012345678"});
        model.addRow(new Object[] {"PC04124", "Nguyễn Văn Hồng Phi", "Nam", "Trà Vinh", "0336761552"});
        model.addRow(new Object[] {"PC04012", "Huỳnh Bảo Khang", "Nam", "Cà Mau", "012345678"});
        model.addRow(new Object[] {"PC03916", "Nguyễn Thị Hồng Thắm", "Nữ", "Hậu Giang", "012345678"});
        model.addRow(new Object[] {"PC04104", "Phạm Văn Vương", "Nam", "Phú Quốc", "012345678"});
        model.addRow(new Object[] {"PC03762", "Phạm Văn Duy", "Nam", "Bạc Liêu", "012345678"});
        tbl.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableCustom1 = new com.system.customSwing.Table_Advance.TableCustom();
        tableScrollButton1 = new com.system.customSwing.Table_Advance.TableScrollButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblList);

        tableScrollButton1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Tên bảng:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.system.customSwing.Table_Advance.TableCustom tableCustom1;
    private com.system.customSwing.Table_Advance.TableScrollButton tableScrollButton1;
    private javax.swing.JTable tblList;
    // End of variables declaration//GEN-END:variables
}
